language: cpp

matrix:
    include:
        - os: linux

sudo: required

addons:
    apt:
        packages:
            - build-essential
            - openssl
            - libssl-dev
            - libpam0g-dev
            - python2.7-dev
            - pkg-config
            - libkrb5-dev

before_install:
    - date
    -
    - # Fetch the Build-omi-script-provider repository for dependencies to build from
    - git config --global 'url.https://github.com/.insteadOf' 'git@github.com:'
    - git clone --recursive 'https://github.com/Microsoft/Build-omi-script-provider.git' ../bld-osp
    -
    - # Master branch for all submodules
    - cd ../bld-osp
    - git submodule foreach git checkout master
    -
    - # Patch in the version of omi-script-provider that Travis gave to us
    - rm -rf scriptprovider
    - cp -R ../omi-script-provider scriptprovider

script:
    - cd scriptprovider
    - ./regress
