#!/bin/bash

REGRESS_RESULT=0
LOG_PATH=`pwd` #path were the stderr result and where stdout and stderr dummy files will be stored temporarly

echo "Stderr dump start" >> "$LOG_PATH/stderr_out"

function run_command {
    $1
    EXIT_RESULT=$?
    if [ "$EXIT_RESULT" = "0" ]; then
        echo ">>> \"$1\" exited succesfully <<<"
    else
        echo ">>> \"$1\" failed with $EXIT_RESULT <<<"
        REGRESS_RESULT=1
    fi
}

run_command "./build.sh"
run_command "./output/bin/test"
run_command "python ./python/test/test.py"
run_command "./test_all $LOG_PATH"


echo "************************"
echo "************************"
echo "************************"
echo "***                  ***"
if [ "$REGRESS_RESULT" = "0" ]; then
    echo "***  Regress passed  ***"
else
    echo "***  Regress failed  ***"
fi
echo "***                  ***"
echo "************************"
echo "************************"
echo "************************"


pushd ../omi/Unix/output/var/log 1>/dev/null 2>&1
LOG_FILES=`ls`
LOG_FILES="$LOG_FILES $LOG_PATH/stderr_out"
for LOG_FILE in $LOG_FILES; do
    echo "---------------------------"
    echo $LOG_FILE
    cat $LOG_FILE
done
popd 1>/dev/null 2>&1

rm "$LOG_PATH/stderr_out"

exit $REGRESS_RESULT
