#!/bin/bash

LOG_PATH=$2
STDERR_FILE="$LOG_PATH/stderr_out"
TMP_1="$LOG_PATH/tmp_1"
TMP_2="$LOG_PATH/tmp_2"

../../../omi/Unix/output/bin/omiserver -s 1>$TMP_1 2>$TMP_2

echo "start_server" >> $STDERR_FILE
echo "-----------------------------" $STDERR_FILE
echo "stdout:" >> $STDERR_FILE
cat $TMP_1 >> $STDERR_FILE
echo "stderr:" >> $STDERR_FILE
cat $TMP_2 >> $STDERR_FILE
rm $TMP_1 $TMP_2 1>/dev/null 2>&1

sleep 1
