#!/bin/bash

LOG_PATH=$1
STDERR_FILE="$LOG_PATH/stderr_out"
TMP_1="$LOG_PATH/tmp_1"
TMP_2="$LOG_PATH/tmp_2"

function DUMP_STD {
    echo "$1" >> $STDERR_FILE
    echo "-----------------------------"
    echo "stdout:" >> $STDERR_FILE
    cat $TMP_1 1>> $STDERR_FILE 2>/dev/null
    echo "stderr:" >> $STDERR_FILE
    cat $TMP_2 1>> $STDERR_FILE 2>/dev/null
    rm $TMP_1 $TMP_2 1>/dev/null 2>&1
}

function start_server {
    rm *.pyc 1>/dev/null 2>&1

    ../../../omi/Unix/output/bin/omireg --Python Full_Test 1>$TMP_1 2>$TMP_2
    DUMP_STD "omireg"
    ../../../omi/Unix/output/bin/omiserver -d 1>$TMP_1 2>$TMP_2
    DUMP_STD "start_server"

    sleep 1
}

function stop_server {
    sleep 1
    ../../../omi/Unix/output/bin/omiserver -s 1>$TMP_1 2>$TMP_2
    DUMP_STD "stop_server"
}

function init_record {
    RECORD_FILE_NAME="../../../omi/Unix/output/lib/FullTestOMI_Record"
    if [ ! -e "$RECORD_FILE_NAME" ]; then
        touch "$RECORD_FILE_NAME"
    fi
}

TEST_RESULT=0
function CHECK {
    diff $1 ../full_test_results/$1
    RESULT=$?
    if [ "$RESULT" = "0" ]; then
        echo "$2 passed!"
    else
        echo "$2 failed!"
        TEST_RESULT=1
    fi
}

pushd full_test_cli 1>/dev/null 2>&1

init_record

export PYTHONPATH=`pwd`

start_server

../../../omi/Unix/output/bin/omicli ci root/cimv2 { Full_Test BooleanTest True RealTest 3.1415 StringTest "Value of PI" } >> step0 2>>$TMP_2
../../../omi/Unix/output/bin/omicli ci root/cimv2 { Full_Test BooleanTest False IntTest 365 StringTest "Days in a year" } >> step0 2>>$TMP_2
../../../omi/Unix/output/bin/omicli ci root/cimv2 { Full_Test BooleanTest False RealTest 1.618 StringTest "Golden ratio" } >> step0 2>>$TMP_2
CHECK step0 "Create three instances"
DUMP_STD "Create three instances"

../../../omi/Unix/output/bin/omicli ei root/cimv2 Full_Test >> step1 2>>$TMP_2
CHECK step1 "Enumerate"
DUMP_STD "Enumerate"

stop_server

start_server
../../../omi/Unix/output/bin/omicli ei root/cimv2 Full_Test >> step2 2>>$TMP_2
CHECK step2 "Reload and enumerate"
DUMP_STD "Reload and enumerate"

../../../omi/Unix/output/bin/omicli ci root/cimv2 { Full_Test BooleanTest True IntTest 256 StringTest "Number of ASCII Symbols" RealTest 9.87 } >> step3 2>>$TMP_2
CHECK step3 "Create another instance"
DUMP_STD "Create another instance"

../../../omi/Unix/output/bin/omicli ei root/cimv2 Full_Test >> step4 2>>$TMP_2
CHECK step4 "Enumerate"
DUMP_STD "Enumerate"

../../../omi/Unix/output/bin/omicli gi root/cimv2 { Full_Test Id 3 } >> step5 2>>$TMP_2
CHECK step5 "Get instance"
DUMP_STD "Get instance"

../../../omi/Unix/output/bin/omicli mi root/cimv2 { Full_Test Id 3 BooleanTest False IntTest 255 StringTest "Max value for ASCII Symbols" RealTest 10.0 } >> step6 2>>$TMP_2
CHECK step6 "Modify instance"
DUMP_STD "Modify instance"

../../../omi/Unix/output/bin/omicli ei root/cimv2 Full_Test >> step7 2>>$TMP_2
CHECK step7 "Enumerate"
DUMP_STD "Enumerate"

../../../omi/Unix/output/bin/omicli di root/cimv2 { Full_Test Id 3 } 2>>$TMP_2
../../../omi/Unix/output/bin/omicli ei root/cimv2 Full_Test >> step8 2>>$TMP_2
CHECK step8 "Delete instance"
DUMP_STD "Delete instance"

../../../omi/Unix/output/bin/omicli di root/cimv2 { Full_Test Id 0 } 2>>$TMP_2
../../../omi/Unix/output/bin/omicli di root/cimv2 { Full_Test Id 1 } 2>>$TMP_2
../../../omi/Unix/output/bin/omicli di root/cimv2 { Full_Test Id 2 } 2>>$TMP_2
../../../omi/Unix/output/bin/omicli ei root/cimv2 Full_Test >> step9 2>>$TMP_2
CHECK step9 "Delete all instances"
DUMP_STD "Delete all instances"


stop_server

rm *.pyc
rm step*

popd 1>/dev/null 2>&1

exit $TEST_RESULT
